[fix] Fixing failing unit tests (#2108)
Datastore ds.URL method was removed as deprecated in vmware govmomi
lib in favour of ds.NewURL but usages in code were not removed causing
unit tests to start failing after the upgrade to govmomi v0.34.2 with:
Error: vsphere/resource_vsphere_file.go:152:19: ds.URL undefined (type *object.Datastore has no field or method URL)

Updated the usages of the deprecated method with the recommended one

Testing done:

Executed `make test` without errors

Signed-off-by: Vasil Atanasov <vasila@vmware.com>