[fix] Error when reading data virtual machine with SRIOV adapter
Fixing error reated to the SRIOV feature:
Error: error setting network interfaces: Invalid address to set: []string{"network_interfaces", "3", "physical_function"}

The issue is that the data source schema is different from the resource
schema and was missing the network_interfaces.#.physical_function
attribute in the schema

Signed-off-by: Vasil Atanasov <vasila@vmware.com>